language: ruby

before_install: gem up bundler

rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.7
  - 2.3.3
  - 2.4.0
  - ruby-head
  - jruby
  - jruby-head
  - rbx-2

gemfile:
  - gemfiles/data_mapper_12.gemfile

sudo: false

script: "bundle exec rake spec"

cache: bundler

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
    - rvm: jruby-head
    - rvm: rbx-2
  fast_finish: true
